name: viral_hrsm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pyyaml
  - biopython
  - statsmodels
  - tabulate
  - beautifulsoup4
  - pip
